version: "3.9"
services:
  db:
    image: postgres:17

    env_file: .env

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d:ro

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 20

  web:
    build: .
    container_name: brake-shop-docker
    env_file: .env

    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      DJANGO_DEBUG: ${DEBUG:-true}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS:-localhost,127.0.0.1}

    depends_on:
      db:
        condition: service_healthy

    volumes:
      - .:/app
      - static:/app/static_root
      - media:/app/media

    ports:
      - "8000:8000"

    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

volumes:
  postgres_data:
  static:
  media:
