# Generated by Django 5.2.4 on 2025-08-23 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('ean', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('available', models.BooleanField(default=False)),
                ('type_label', models.CharField(blank=True, default='', max_length=100)),
                ('image_url', models.URLField(blank=True, default='')),
                ('technical_image_url', models.URLField(blank=True, default='')),
                ('diameter_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('thickness_th_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('min_thickness_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('height_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('num_holes', models.IntegerField(blank=True, null=True)),
                ('disc_type', models.CharField(blank=True, choices=[('S', 'Solid'), ('V', 'Ventilated')], max_length=1, null=True)),
                ('center_bore_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('tightening_torque', models.IntegerField(blank=True, null=True)),
                ('axle', models.CharField(blank=True, choices=[('F', 'Front'), ('R', 'Rear'), ('B', 'Front and rear')], max_length=1, null=True)),
                ('assembly_side', models.CharField(blank=True, choices=[('N', 'None'), ('L', 'Left'), ('R', 'Right'), ('B', 'Left and right')], default='B', max_length=1, null=True)),
                ('units_per_box', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
                'unique_together': {('code', 'ean')},
            },
        ),
    ]
