# Generated by Django 5.2.6 on 2025-12-10 23:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=190, unique=True)),
                ('slug', models.SlugField(max_length=190, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('website', models.URLField(blank=True, default='')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brand-logos/')),
                ('country', models.CharField(blank=True, default='', max_length=80)),
                ('oem', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=190)),
                ('slug', models.SlugField(max_length=190, unique=True)),
                ('input_type', models.CharField(choices=[('text', 'Text'), ('int', 'Integer'), ('dec', 'Decimal'), ('bool', 'Boolean'), ('select', 'Select (single)'), ('multiselect', 'Select (multiple)')], default='text', max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('is_filterable', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['is_filterable', 'sort_order'], name='catalogue_a_is_filt_2a28c8_idx')],
            },
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('value', models.CharField(max_length=190)),
                ('slug', models.SlugField(blank=True, default='', max_length=190)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='catalogue.attribute')),
            ],
            options={
                'ordering': ['attribute_id', 'sort_order', 'value'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=190)),
                ('slug', models.SlugField(max_length=190, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalogue.category')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=190)),
                ('slug', models.SlugField(max_length=190, unique=True)),
                ('sku', models.CharField(db_index=True, max_length=64, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('visible', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('ean', models.CharField(blank=True, db_index=True, default='', max_length=14)),
                ('mpn', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('price_compare_at', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('promo_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('promo_starts_at', models.DateTimeField(blank=True, null=True)),
                ('promo_ends_at', models.DateTimeField(blank=True, null=True)),
                ('vat_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('stock_qty', models.IntegerField(default=0)),
                ('reserved_qty', models.PositiveIntegerField(default=0)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('length_mm', models.PositiveIntegerField(blank=True, null=True)),
                ('width_mm', models.PositiveIntegerField(blank=True, null=True)),
                ('height_mm', models.PositiveIntegerField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('meta_title', models.CharField(blank=True, default='', max_length=190)),
                ('meta_description', models.CharField(blank=True, default='', max_length=255)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalogue.brand')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('value_text', models.CharField(blank=True, default='', max_length=255)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_attributes', to='catalogue.attribute')),
                ('attribute_value', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_attributes', to='catalogue.attributevalue')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_attributes', to='catalogue.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='products', through='catalogue.ProductCategory', to='catalogue.category'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=190)),
                ('image', models.ImageField(upload_to='product-images/')),
                ('alt_text', models.CharField(blank=True, default='', max_length=190)),
                ('is_primary', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalogue.product')),
            ],
            options={
                'ordering': ['product_id', 'sort_order', '-is_primary'],
            },
        ),
        migrations.CreateModel(
            name='ProductVehicleCompatibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('displacement_year', models.ForeignKey(blank=True, help_text='For bikes', null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicles.displacementyear')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_compatibilities', to='catalogue.product')),
                ('vehicle_type', models.ForeignKey(blank=True, help_text='For cars/CVs', null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicles.types')),
            ],
        ),
        migrations.AddIndex(
            model_name='attributevalue',
            index=models.Index(fields=['attribute', 'sort_order'], name='catalogue_a_attribu_703c6c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attributevalue',
            unique_together={('attribute', 'value')},
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent', 'is_active'], name='catalogue_c_parent__be2998_idx'),
        ),
        migrations.AddIndex(
            model_name='productattribute',
            index=models.Index(fields=['product', 'attribute'], name='catalogue_p_product_d67334_idx'),
        ),
        migrations.AddIndex(
            model_name='productattribute',
            index=models.Index(fields=['attribute_value'], name='catalogue_p_attribu_60638e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productattribute',
            unique_together={('product', 'attribute')},
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['category', 'product'], name='catalogue_p_categor_effd26_idx'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['is_primary'], name='catalogue_p_is_prim_ca3645_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productcategory',
            unique_together={('product', 'category')},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'visible'], name='catalogue_p_is_acti_5dcecb_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='catalogue_p_name_7c6733_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand', 'is_active'], name='catalogue_p_brand_i_758cd4_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['published_at'], name='catalogue_p_publish_17dfd0_idx'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product', 'is_primary'], name='catalogue_p_product_498ad7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productimage',
            unique_together={('product', 'sort_order')},
        ),
        migrations.AddIndex(
            model_name='productvehiclecompatibility',
            index=models.Index(fields=['product'], name='catalogue_p_product_2da571_idx'),
        ),
        migrations.AddIndex(
            model_name='productvehiclecompatibility',
            index=models.Index(fields=['vehicle_type'], name='catalogue_p_vehicle_ff21b2_idx'),
        ),
        migrations.AddIndex(
            model_name='productvehiclecompatibility',
            index=models.Index(fields=['displacement_year'], name='catalogue_p_displac_22fccf_idx'),
        ),
        migrations.AddConstraint(
            model_name='productvehiclecompatibility',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('displacement_year__isnull', True), ('vehicle_type__isnull', False)), models.Q(('displacement_year__isnull', False), ('vehicle_type__isnull', True)), _connector='OR'), name='exactly_one_vehicle_reference'),
        ),
        migrations.AddConstraint(
            model_name='productvehiclecompatibility',
            constraint=models.UniqueConstraint(condition=models.Q(('vehicle_type__isnull', False)), fields=('product', 'vehicle_type'), name='unique_product_type'),
        ),
        migrations.AddConstraint(
            model_name='productvehiclecompatibility',
            constraint=models.UniqueConstraint(condition=models.Q(('displacement_year__isnull', False)), fields=('product', 'displacement_year'), name='unique_product_displacement'),
        ),
    ]
