# Generated by Django 5.2.6 on 2025-12-11 10:56

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='attribute_value',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='attribute', chained_model_field='attribute', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_attributes', to='catalogue.attributevalue'),
        ),
        migrations.AlterField(
            model_name='productvehiclecompatibility',
            name='displacement_year',
            field=models.ForeignKey(blank=True, help_text='For bikes', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_compatibilities', to='vehicles.displacementyear'),
        ),
        migrations.AlterField(
            model_name='productvehiclecompatibility',
            name='vehicle_type',
            field=models.ForeignKey(blank=True, help_text='For cars/CVs', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_compatibilities', to='vehicles.types'),
        ),
    ]
