# Generated by Django 5.2.6 on 2025-12-09 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
        ('vehicles', '0004_brands_brembo_code_displacements_brembo_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVehicleCompatibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('displacement_year', models.ForeignKey(blank=True, help_text='For bikes', null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicles.displacementyear')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_compatibilities', to='catalogue.product')),
                ('vehicle_type', models.ForeignKey(blank=True, help_text='For cars/CVs', null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicles.types')),
            ],
            options={
                'indexes': [models.Index(fields=['product'], name='catalogue_p_product_2da571_idx'), models.Index(fields=['vehicle_type'], name='catalogue_p_vehicle_ff21b2_idx'), models.Index(fields=['displacement_year'], name='catalogue_p_displac_22fccf_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('displacement_year__isnull', True), ('vehicle_type__isnull', False)), models.Q(('displacement_year__isnull', False), ('vehicle_type__isnull', True)), _connector='OR'), name='exactly_one_vehicle_reference'), models.UniqueConstraint(condition=models.Q(('vehicle_type__isnull', False)), fields=('product', 'vehicle_type'), name='unique_product_type'), models.UniqueConstraint(condition=models.Q(('displacement_year__isnull', False)), fields=('product', 'displacement_year'), name='unique_product_displacement')],
            },
        ),
    ]
