# Generated by Django 5.2.6 on 2026-01-11 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_alter_productattribute_attribute_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sync_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
