# Generated by Django 5.2.4 on 2025-08-24 00:36

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_clutchcylinder_clutchmastercylinder_mastercylinder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PadAccessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('ean', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('available', models.BooleanField(default=False)),
                ('type_label', models.CharField(blank=True, default='', max_length=100)),
                ('image_url', models.URLField(blank=True, default='')),
                ('technical_image_url', models.URLField(blank=True, default='')),
                ('braking_system', models.CharField(blank=True, max_length=30, null=True)),
                ('accessory_type', models.CharField(blank=True, choices=[('W', 'Wear Indicator'), ('A', 'Assembly Kit')], max_length=1, null=True)),
                ('axle', models.CharField(blank=True, choices=[('F', 'Front'), ('R', 'Rear'), ('B', 'Front and rear')], max_length=1, null=True)),
                ('length_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('assembly_side', models.CharField(blank=True, choices=[('N', 'None'), ('L', 'Left'), ('R', 'Right'), ('B', 'Left and right')], max_length=1, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProportioningValve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('ean', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('available', models.BooleanField(default=False)),
                ('type_label', models.CharField(blank=True, default='', max_length=100)),
                ('image_url', models.URLField(blank=True, default='')),
                ('technical_image_url', models.URLField(blank=True, default='')),
                ('threading', models.CharField(blank=True, max_length=30, null=True)),
                ('material', models.CharField(blank=True, choices=[('A', 'Aluminium'), ('CA', 'Cast Iron'), ('P', 'Plastic'), ('S', 'Steel')], max_length=2, null=True)),
                ('braking_system', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='PadAccessories',
        ),
        migrations.DeleteModel(
            name='ProportioningValves',
        ),
        migrations.RenameField(
            model_name='caliper',
            old_name='breaking_system',
            new_name='braking_system',
        ),
        migrations.RenameField(
            model_name='clutchcylinder',
            old_name='breaking_system',
            new_name='braking_system',
        ),
        migrations.RenameField(
            model_name='clutchmastercylinder',
            old_name='breaking_system',
            new_name='braking_system',
        ),
        migrations.RenameField(
            model_name='mastercylinder',
            old_name='breaking_system',
            new_name='braking_system',
        ),
        migrations.RenameField(
            model_name='pad',
            old_name='WVA_number',
            new_name='braking_system',
        ),
        migrations.RenameField(
            model_name='pad',
            old_name='FMSI',
            new_name='fmsi',
        ),
        migrations.RenameField(
            model_name='pad',
            old_name='breaking_system',
            new_name='wva_number',
        ),
        migrations.RenameField(
            model_name='shoe',
            old_name='breaking_system',
            new_name='braking_system',
        ),
        migrations.RenameField(
            model_name='shoe',
            old_name='has_handbrake_level',
            new_name='has_handbrake_lever',
        ),
        migrations.RenameField(
            model_name='shoekit',
            old_name='breaking_system',
            new_name='braking_system',
        ),
        migrations.RenameField(
            model_name='shoekit',
            old_name='is_manuel_proportioning_valve',
            new_name='is_manual_proportioning_valve',
        ),
        migrations.RenameField(
            model_name='wheelcylinder',
            old_name='breaking_system',
            new_name='braking_system',
        ),
        migrations.AlterUniqueTogether(
            name='caliper',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='disc',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='hose',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='kit',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='pad',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='shoe',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='shoekit',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='caliper',
            name='code',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='caliper',
            name='num_pistons',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caliper',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='clutchcylinder',
            name='code',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='clutchcylinder',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='clutchmastercylinder',
            name='code',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='clutchmastercylinder',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='disc',
            name='assembly_side',
            field=models.CharField(blank=True, choices=[('N', 'None'), ('L', 'Left'), ('R', 'Right'), ('B', 'Left and right')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='disc',
            name='axle',
            field=models.CharField(blank=True, choices=[('F', 'Front'), ('R', 'Rear'), ('B', 'Front and rear')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='disc',
            name='code',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='disc',
            name='num_holes',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='disc',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='disc',
            name='tightening_torque',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='disc',
            name='units_per_box',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hose',
            name='code',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='hose',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='kit',
            name='code',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='kit',
            name='disc_per_box',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kit',
            name='pad_per_box',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kit',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='mastercylinder',
            name='code',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='mastercylinder',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='pad',
            name='axle',
            field=models.CharField(blank=True, choices=[('F', 'Front'), ('R', 'Rear'), ('B', 'Front and rear')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='pad',
            name='code',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='pad',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='code',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='shoekit',
            name='code',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='shoekit',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='wheelcylinder',
            name='code',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='wheelcylinder',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddConstraint(
            model_name='disc',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('assembly_side__in', ['N', 'B']), ('axle', 'B')), models.Q(('assembly_side__in', ['N', 'L', 'R']), ('axle__in', ['F', 'R'])), ('axle__isnull', True), ('axle', ''), _connector='OR'), name='disc_valid_axle_side'),
        ),
        migrations.AddConstraint(
            model_name='mastercylinder',
            constraint=models.CheckConstraint(condition=models.Q(('axle', 'R'), ('axle__isnull', True), ('axle', ''), _connector='OR'), name='master_cyl_rear_only'),
        ),
    ]
