# Generated by Django 5.2.4 on 2025-08-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_padaccessory_proportioningvalve_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caliper',
            name='id',
        ),
        migrations.RemoveField(
            model_name='clutchcylinder',
            name='id',
        ),
        migrations.RemoveField(
            model_name='clutchmastercylinder',
            name='id',
        ),
        migrations.RemoveField(
            model_name='disc',
            name='id',
        ),
        migrations.RemoveField(
            model_name='hose',
            name='id',
        ),
        migrations.RemoveField(
            model_name='kit',
            name='id',
        ),
        migrations.RemoveField(
            model_name='mastercylinder',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pad',
            name='id',
        ),
        migrations.RemoveField(
            model_name='padaccessory',
            name='id',
        ),
        migrations.RemoveField(
            model_name='proportioningvalve',
            name='id',
        ),
        migrations.RemoveField(
            model_name='shoe',
            name='id',
        ),
        migrations.RemoveField(
            model_name='shoekit',
            name='id',
        ),
        migrations.RemoveField(
            model_name='wheelcylinder',
            name='id',
        ),
        migrations.AddField(
            model_name='caliper',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clutchcylinder',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clutchmastercylinder',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='disc',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hose',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kit',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mastercylinder',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pad',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='padaccessory',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proportioningvalve',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shoe',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shoekit',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wheelcylinder',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='caliper',
            name='code',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='clutchcylinder',
            name='code',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='clutchcylinder',
            name='material',
            field=models.CharField(blank=True, choices=[('A', 'Aluminium'), ('C', 'Cast Iron'), ('P', 'Plastic'), ('S', 'Steel')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='clutchmastercylinder',
            name='code',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='clutchmastercylinder',
            name='material',
            field=models.CharField(blank=True, choices=[('A', 'Aluminium'), ('C', 'Cast Iron'), ('P', 'Plastic'), ('S', 'Steel')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='disc',
            name='code',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='hose',
            name='code',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='kit',
            name='code',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='mastercylinder',
            name='code',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='mastercylinder',
            name='material',
            field=models.CharField(blank=True, choices=[('A', 'Aluminium'), ('C', 'Cast Iron'), ('P', 'Plastic'), ('S', 'Steel')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='pad',
            name='code',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='padaccessory',
            name='code',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='proportioningvalve',
            name='code',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='proportioningvalve',
            name='material',
            field=models.CharField(blank=True, choices=[('A', 'Aluminium'), ('C', 'Cast Iron'), ('P', 'Plastic'), ('S', 'Steel')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='code',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='shoekit',
            name='code',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='wheelcylinder',
            name='code',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='wheelcylinder',
            name='material',
            field=models.CharField(blank=True, choices=[('A', 'Aluminium'), ('C', 'Cast Iron'), ('P', 'Plastic'), ('S', 'Steel')], max_length=1, null=True),
        ),
    ]
