# Generated by Django 5.2.6 on 2026-01-12 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_categoryattribute'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryattribute',
            options={'ordering': ['sort_order', 'attribute__name']},
        ),
        migrations.AddField(
            model_name='categoryattribute',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='categoryattribute',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_attributes', to='catalogue.attribute'),
        ),
        migrations.AlterField(
            model_name='categoryattribute',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_attributes', to='catalogue.category'),
        ),
    ]
