# Generated by Django 5.2.4 on 2025-08-25 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_remove_caliper_id_remove_clutchcylinder_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caliper',
            name='assembly_side',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Left'), ('R', 'Right'), ('B', 'Left and right')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='disc',
            name='assembly_side',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Left'), ('R', 'Right'), ('B', 'Left and right')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='padaccessory',
            name='assembly_side',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Left'), ('R', 'Right'), ('B', 'Left and right')], default='N', max_length=1),
        ),
    ]
