# Generated by Django 5.2.4 on 2025-08-25 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_alter_caliper_assembly_side_alter_disc_assembly_side_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='disc',
            name='disc_valid_axle_side',
        ),
    ]
