# Generated by Django 5.2.4 on 2025-08-27 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_remove_disc_disc_valid_axle_side'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.PositiveIntegerField()),
                ('vehicle_id', models.PositiveIntegerField()),
                ('product_ct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
                ('vehicle_ct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'indexes': [models.Index(fields=['product_ct', 'product_id'], name='catalogue_p_product_d031c9_idx'), models.Index(fields=['vehicle_ct', 'vehicle_id'], name='catalogue_p_vehicle_af3d05_idx')],
                'constraints': [models.UniqueConstraint(fields=('product_ct', 'product_id', 'vehicle_ct', 'vehicle_id'), name='uniq_product_vehicle')],
            },
        ),
    ]
