# Generated by Django 5.2.4 on 2025-08-27 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_productvehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvehicle',
            name='product_id',
            field=models.CharField(max_length=30),
        ),
    ]
