# Generated by Django 5.2.4 on 2025-08-29 16:26

import catalogue.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0008_alter_productvehicle_product_id'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvehicle',
            name='product_ct',
            field=models.ForeignKey(limit_choices_to=catalogue.models.product_ct_limit, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='productvehicle',
            name='vehicle_ct',
            field=models.ForeignKey(limit_choices_to=catalogue.models.vehicle_ct_limit, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.CreateModel(
            name='Drum',
            fields=[
                ('code', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('ean', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('available', models.BooleanField(default=False)),
                ('type_label', models.CharField(blank=True, default='', max_length=100)),
                ('image_url', models.URLField(blank=True, default='')),
                ('technical_image_url', models.URLField(blank=True, default='')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('diameter_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('width_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('height_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('num_holes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('center_bore_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('max_diameter_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('axle', models.CharField(blank=True, choices=[('F', 'Front'), ('R', 'Rear'), ('B', 'Front and rear')], max_length=1, null=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('max_diameter_mm__isnull', True), ('diameter_mm__isnull', True), ('max_diameter_mm__gt', models.F('diameter_mm')), _connector='OR'), name='drum_max_diameter_gt_diameter')],
            },
        ),
    ]
