# Generated by Django 5.2.4 on 2025-09-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0009_alter_productvehicle_product_ct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pad',
            name='wva_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
