# Generated by Django 5.2.4 on 2025-09-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0010_alter_pad_wva_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='padaccessory',
            options={'verbose_name_plural': 'Pad Accessories'},
        ),
        migrations.AlterModelOptions(
            name='productvehicle',
            options={'verbose_name_plural': 'Product Vehicles'},
        ),
        migrations.AlterField(
            model_name='clutchcylinder',
            name='threading',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clutchmastercylinder',
            name='threading',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mastercylinder',
            name='threading',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='wheelcylinder',
            name='threading',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
