# Generated by Django 5.2.4 on 2025-09-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0011_alter_padaccessory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caliper',
            name='assembly_side',
            field=models.CharField(blank=True, choices=[('L', 'Left'), ('R', 'Right'), ('B', 'Left and right')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='disc',
            name='assembly_side',
            field=models.CharField(blank=True, choices=[('L', 'Left'), ('R', 'Right'), ('B', 'Left and right')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='padaccessory',
            name='assembly_side',
            field=models.CharField(blank=True, choices=[('L', 'Left'), ('R', 'Right'), ('B', 'Left and right')], max_length=1, null=True),
        ),
    ]
