# Generated by Django 5.2.6 on 2025-12-10 23:25

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('brembo_code', models.CharField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='Years',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('value', models.IntegerField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Years',
            },
        ),
        migrations.CreateModel(
            name='Models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('brembo_code', models.CharField(blank=True, null=True, unique=True)),
                ('vehicle_type', models.CharField(choices=[('c', 'Car'), ('t', 'Commercial Vehicle'), ('b', 'Motorbike')], default='c', max_length=1)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.brands')),
            ],
            options={
                'verbose_name_plural': 'Models',
            },
        ),
        migrations.CreateModel(
            name='Displacements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('brembo_code', models.CharField(blank=True, null=True, unique=True)),
                ('value', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.brands')),
                ('model', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='brand', chained_model_field='brand', limit_choices_to=models.Q(('vehicle_type__in', ['b'])), on_delete=django.db.models.deletion.CASCADE, to='vehicles.models')),
            ],
            options={
                'verbose_name_plural': 'Displacements',
            },
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('brembo_code', models.CharField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('kw', models.IntegerField()),
                ('cv', models.IntegerField()),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.brands')),
                ('model', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='brand', chained_model_field='brand', limit_choices_to=models.Q(('vehicle_type__in', ['c', 't'])), on_delete=django.db.models.deletion.CASCADE, to='vehicles.models')),
            ],
            options={
                'verbose_name_plural': 'Types',
            },
        ),
        migrations.CreateModel(
            name='DisplacementYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('displacement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.displacements')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.years')),
            ],
            options={
                'verbose_name_plural': 'Displacement-Years',
            },
        ),
        migrations.AddIndex(
            model_name='models',
            index=models.Index(fields=['vehicle_type', 'brand'], name='vehicles_mo_vehicle_834613_idx'),
        ),
        migrations.AddIndex(
            model_name='displacements',
            index=models.Index(fields=['brand'], name='vehicles_di_brand_i_18a0e7_idx'),
        ),
        migrations.AddIndex(
            model_name='displacements',
            index=models.Index(fields=['model'], name='vehicles_di_model_i_bbf552_idx'),
        ),
        migrations.AddIndex(
            model_name='types',
            index=models.Index(fields=['model'], name='vehicles_ty_model_i_499834_idx'),
        ),
        migrations.AddIndex(
            model_name='types',
            index=models.Index(fields=['slug'], name='vehicles_ty_slug_f424aa_idx'),
        ),
        migrations.AddIndex(
            model_name='displacementyear',
            index=models.Index(fields=['displacement'], name='vehicles_di_displac_227b4f_idx'),
        ),
        migrations.AddIndex(
            model_name='displacementyear',
            index=models.Index(fields=['slug'], name='vehicles_di_slug_205802_idx'),
        ),
        migrations.AddConstraint(
            model_name='displacementyear',
            constraint=models.UniqueConstraint(fields=('displacement', 'year'), name='unique_displacement_year'),
        ),
    ]
