# Generated by Django 5.2.6 on 2025-10-01 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_id', models.BigIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='Years',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_id', models.BigIntegerField(blank=True, null=True)),
                ('value', models.IntegerField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Years',
            },
        ),
        migrations.CreateModel(
            name='Models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_id', models.BigIntegerField(blank=True, null=True)),
                ('vehicle_type', models.CharField(choices=[('c', 'Car'), ('t', 'Commercial Vehicle'), ('b', 'Motorbike')], default='c', max_length=1)),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.brands')),
            ],
            options={
                'verbose_name_plural': 'Models',
            },
        ),
        migrations.CreateModel(
            name='Displacements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_id', models.BigIntegerField(blank=True, null=True)),
                ('value', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.brands')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.models')),
            ],
            options={
                'verbose_name_plural': 'Displacements',
            },
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_id', models.BigIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('kw', models.IntegerField()),
                ('cv', models.IntegerField()),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.brands')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.models')),
            ],
            options={
                'verbose_name_plural': 'Types',
            },
        ),
        migrations.CreateModel(
            name='DisplacementYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_id', models.BigIntegerField(blank=True, null=True)),
                ('displacement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.displacements')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.years')),
            ],
        ),
        migrations.AddIndex(
            model_name='models',
            index=models.Index(fields=['vehicle_type', 'brand'], name='vehicles_mo_vehicle_834613_idx'),
        ),
        migrations.AddIndex(
            model_name='displacements',
            index=models.Index(fields=['brand'], name='vehicles_di_brand_i_18a0e7_idx'),
        ),
        migrations.AddIndex(
            model_name='displacements',
            index=models.Index(fields=['model'], name='vehicles_di_model_i_bbf552_idx'),
        ),
        migrations.AddIndex(
            model_name='types',
            index=models.Index(fields=['brand'], name='vehicles_ty_brand_i_7116ca_idx'),
        ),
        migrations.AddIndex(
            model_name='types',
            index=models.Index(fields=['model'], name='vehicles_ty_model_i_499834_idx'),
        ),
    ]
