# Generated by Django 5.2.6 on 2025-10-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='displacementyear',
            options={'verbose_name_plural': 'Displacement-Years'},
        ),
        migrations.AddIndex(
            model_name='displacementyear',
            index=models.Index(fields=['displacement'], name='vehicles_di_displac_227b4f_idx'),
        ),
    ]
