# Generated by Django 5.2.4 on 2025-08-01 22:10

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.ForeignKey(limit_choices_to={'vehicle_type': None}, on_delete=django.db.models.deletion.CASCADE, to='vehicles.brand'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='brand', chained_model_field='brand', on_delete=django.db.models.deletion.CASCADE, to='vehicles.model'),
        ),
        migrations.AlterField(
            model_name='commercialvehicle',
            name='brand',
            field=models.ForeignKey(limit_choices_to={'vehicle_type': None}, on_delete=django.db.models.deletion.CASCADE, to='vehicles.brand'),
        ),
        migrations.AlterField(
            model_name='commercialvehicle',
            name='model',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='brand', chained_model_field='brand', on_delete=django.db.models.deletion.CASCADE, to='vehicles.model'),
        ),
        migrations.AlterField(
            model_name='motorbike',
            name='brand',
            field=models.ForeignKey(limit_choices_to={'vehicle_type': None}, on_delete=django.db.models.deletion.CASCADE, to='vehicles.brand'),
        ),
        migrations.AlterField(
            model_name='motorbike',
            name='model',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='brand', chained_model_field='brand', on_delete=django.db.models.deletion.CASCADE, to='vehicles.model'),
        ),
    ]
