# Generated by Django 5.2.6 on 2025-10-01 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='types',
            name='model',
            field=models.ForeignKey(limit_choices_to=models.Q(('vehicle_type_in', ['c', 't'])), on_delete=django.db.models.deletion.CASCADE, to='vehicles.models'),
        ),
    ]
