# Generated by Django 5.2.6 on 2025-12-07 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_alter_displacementyear_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='types',
            name='vehicles_ty_brand_i_7116ca_idx',
        ),
        migrations.AlterField(
            model_name='displacementyear',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='models',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='types',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='displacementyear',
            index=models.Index(fields=['slug'], name='vehicles_di_slug_205802_idx'),
        ),
        migrations.AddIndex(
            model_name='types',
            index=models.Index(fields=['slug'], name='vehicles_ty_slug_f424aa_idx'),
        ),
        migrations.AddConstraint(
            model_name='displacementyear',
            constraint=models.UniqueConstraint(fields=('displacement', 'year'), name='unique_displacement_year'),
        ),
    ]
