# Generated by Django 5.2.6 on 2025-10-03 09:11

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_alter_types_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displacements',
            name='model',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='brand', chained_model_field='brand', limit_choices_to=models.Q(('vehicle_type__in', ['b'])), on_delete=django.db.models.deletion.CASCADE, to='vehicles.models'),
        ),
        migrations.AlterField(
            model_name='types',
            name='model',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='brand', chained_model_field='brand', limit_choices_to=models.Q(('vehicle_type__in', ['c', 't'])), on_delete=django.db.models.deletion.CASCADE, to='vehicles.models'),
        ),
    ]
