# Generated by Django 5.2.4 on 2025-08-01 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_alter_car_brand_alter_car_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.ForeignKey(limit_choices_to={'vehicle_type': 'c'}, on_delete=django.db.models.deletion.CASCADE, to='vehicles.brand'),
        ),
        migrations.AlterField(
            model_name='commercialvehicle',
            name='brand',
            field=models.ForeignKey(limit_choices_to={'vehicle_type': 't'}, on_delete=django.db.models.deletion.CASCADE, to='vehicles.brand'),
        ),
        migrations.AlterField(
            model_name='motorbike',
            name='brand',
            field=models.ForeignKey(limit_choices_to={'vehicle_type': 'b'}, on_delete=django.db.models.deletion.CASCADE, to='vehicles.brand'),
        ),
    ]
