# Generated by Django 5.2.4 on 2025-08-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_alter_car_brand_alter_commercialvehicle_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='date_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='date_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
