# Generated by Django 5.2.6 on 2025-12-09 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_remove_types_vehicles_ty_brand_i_7116ca_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brands',
            name='brembo_code',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='displacements',
            name='brembo_code',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='models',
            name='brembo_code',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='types',
            name='brembo_code',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
    ]
