# Generated by Django 5.2.4 on 2025-08-25 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_alter_model_date_end_alter_model_date_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='vehicle_type',
            field=models.CharField(choices=[('c', 'Car'), ('t', 'Commercial Vehicle'), ('b', 'Motorbike')], max_length=1),
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.ForeignKey(limit_choices_to={'vehicle_type': 'c'}, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='vehicles.brand'),
        ),
    ]
