# Generated by Django 5.2.6 on 2025-12-09 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_brands_brembo_code_displacements_brembo_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='models',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
