# Generated by Django 5.2.6 on 2025-12-09 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_alter_models_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='models',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
