# Generated by Django 5.2.6 on 2025-12-09 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_alter_models_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='types',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='types',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
