# Generated by Django 5.2.6 on 2025-12-09 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_alter_types_name_alter_types_slug'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='types',
            name='unique_model_name',
        ),
    ]
