# Generated by Django 5.2.6 on 2025-12-09 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0010_alter_types_brembo_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='types',
            name='brembo_code',
            field=models.CharField(blank=True, null=True),
        ),
    ]
