# Generated by Django 5.2.6 on 2025-12-09 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0011_alter_types_brembo_code'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='displacements',
            name='unique_model_value',
        ),
    ]
