# Generated by Django 5.2.6 on 2025-12-09 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0012_remove_displacements_unique_model_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displacementyear',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
